# Generated by Django 4.2.3 on 2023-07-11 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('title', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_scan',
            },
        ),
        migrations.CreateModel(
            name='Repo_Scanned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_url', models.URLField()),
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RepoAnalysisApp.scan')),
            ],
            options={
                'db_table': 'repo_scanned',
            },
        ),
    ]
