<<<<<<< HEAD
# Generated by Django 4.2.3 on 2023-07-12 01:48
import django.db.models.deletion
=======
# Generated by Django 4.2.3 on 2023-07-12 23:36

>>>>>>> 0047c1d (Test Database 2)
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):
    initial = True
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_scan',
            },
        ),
<<<<<<< HEAD
    ]
=======
        migrations.CreateModel(
            name='User_Scans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url_name', models.URLField()),
                ('scan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RepoAnalysisApp.scan')),
            ],
            options={
                'db_table': 'user_scaned_repo',
            },
        ),
    ]
>>>>>>> 0047c1d (Test Database 2)
